#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoC                                                                              #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.11                                                                             #
# Filename   : /config/persistence.yml                                                             #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                      #
# URL        : https://github.com/variancexplained/appvoc                                          #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 12:01:04 pm                                                #
# Modified   : Sunday June 30th 2024 02:07:36 am                                                   #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #


# ------------------------------------------------------------------------------------------------ #
#                                         PERSISTENCE                                              #
# ------------------------------------------------------------------------------------------------ #
database:
  name:
    prod: appvoc
    raw:  appvoc_raw
    test: appvoc_test
  backup:
    prod: data/prod/database
    raw: data/raw/database
    test: tests/data/database

file:
  archive:
    prod: data/prod/archive
    raw: data/raw/archive
    test: tests/data/archive
  staging:
    prod: data/prod/archive/staging
    raw: data/raw/archive/staging
    test: tests/data/archive/staging
  datasets:
    prod: data/prod/datasets
    raw: data/raw/datasets
    test: tests/data/datasets

cloud:
  aws_bucket: appvoc
  aws_app_folder: app
  aws_review_folder: reviews