#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoC Ratings & Reviews Analysis                                                 #
# Version    : 0.1.19                                                                              #
# Python     : 3.10.11                                                                             #
# Filename   : /config/persistence.yml                                                             #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                      #
# URL        : https://github.com/variancexplained/appvoc                                           #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 12:01:04 pm                                                #
# Modified   : Thursday August 31st 2023 09:15:53 am                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #


# ------------------------------------------------------------------------------------------------ #
#                                         PERSISTENCE                                              #
# ------------------------------------------------------------------------------------------------ #
database:
  name:
    prod: appvoc
    raw:  appvoc_raw
    test: appvoc_test
  backup:
    prod: data/prod/database
    raw: data/raw/database
    test: tests/data/database

file:
  archive:
    prod: data/prod/archive
    raw: data/raw/archive
    test: tests/data/archive
  staging:
    prod: data/prod/archive/staging
    raw: data/raw/archive/staging
    test: tests/data/archive/staging
  datasets:
    prod: data/prod/datasets
    raw: data/raw/datasets
    test: tests/data/datasets

cloud:
  aws_bucket:
    prod: appvoc-final
    raw: appvoc-raw
    test: appvoc-tests